### PR TITLE
#68 Integrate RDR embeddable figshare content to UCLH research discov…

### PR DESCRIPTION
**Pull request by lawrencelai**
Issue ref : https://github.com/UCLH-Foundry/uclh-research-discovery/issues/68

I embedded the RDR figshare iframe into the "Detecting misplaced NG tubes" data card.
All synthetic data (synthetic CXR and synthetic EHR CSV) are stored in RDR now instead of the GitHub repo.

**Author Checklist**
As author of this pull request I confirm:

- [X]  This submission does not include, or link to any sensitive or person identifiable data
- [X]  I have permission from my co-investigators on the project to publish this information
- [X]  I understand that I have the right to add, amend or remove information published about the project

**Reviewer Checklist**
Reviewers should confirm the following:

- [ ]  These changes are limited to the creation of a new folder under /_projects/ and new content within that folder or these changes update one existing project
- [ ]  Running bundle exec jekyll serve on their local machine builds the site without any errors
- [ ]  The display of the new content appears normal and there are no obviously broken or missing elements on the page
- [ ]  The content has been read and checked for offensive material or spam

### CODE REVIEW

**Comment by uy-rrodriguez** [comment]
Changed reviewer to Steve and updated the code that automatically assigned it to Tom or Amanda.
I had to merge those changes into your branch for the PR to be valid.
In the future, I recommend pushing to a project-specific branch, to avoid conflicts with general updates to the base code. Maybe worth updating the guidance.

**Review by docsteveharris — APPROVED** [review]
I'm approving but assume that you've completed the checks that Tom outlined in the pull request template https://github.com/UCLH-Foundry/uclh-research-discovery/blob/main/.github/PULL_REQUEST_TEMPLATE.md?

**Comment by docsteveharris** [comment]
> I'm approving but assume that you've completed the checks that Tom outlined in the pull request template https://github.com/UCLH-Foundry/uclh-research-discovery/blob/main/.github/PULL_REQUEST_TEMPLATE.md?

@lawrencelai if this ☝️is true then please merge, close and delete the branch once done

**Comment by lawrencelai** [comment]
I have added the Author checklist for this pull request. 
@uy-rrodriguez Can you help to merge this PR? I have no permission to merge.

**Pull request merged**
