### PR TITLE
Docker files and updated Gemfile for local dev

### PR DESCRIPTION
**Pull request by uy-rrodriguez**
Added Docker configuration files to run Jekyll site using Docker.
Updated Gemfile because some libraries didn't work in the Alpine image.

### CODE REVIEW

**Comment by docsteveharris** [comment]
@tcouch would you be able to review? I don't have the knowledge to comment. Sorry - I know you're not on this any more

**Comment by uy-rrodriguez** [comment]
I need to review this PR. It's internal work. I've been testing a few updates on a different fork to not impact this published website, but will merge all updates here in time, and check whether this PR is still valid.

**Comment by tcouch** [comment]
Sorry @docsteveharris, @uy-rrodriguez I only just saw the notification about this. Do you still want me to review? Happy to do so.

**Comment by uy-rrodriguez** [comment]
> Sorry @docsteveharris, @uy-rrodriguez I only just saw the notification about this. Do you still want me to review? Happy to do so.

Let me see if the PR is still needed first and I'll come back to you :)

**Comment by uy-rrodriguez** [comment]
Confirmed, this PR should have been closed a while ago.

**Pull request closed without merging**
