### PR TITLE
Create a new synthetic data project for demo use (NGTUBE and CCHIC)

### PR DESCRIPTION
**Pull request by lawrencelai**
This pull request is to create a new synthetic data project(NGTUBE and CCHIC, demo use).

1. All Attached CSV files were generated by the Turing tool (sqlsynthgen) with the specific vocabulary data set (NGTUBE and CCHIC) 
2. All omop data is randomly generated by predefined man-made rules and outside GAE env.
3. CSV files will be deleted and relinked to RDR once RDR access is ready.

### CODE REVIEW

**Comment by uy-rrodriguez** [comment]
Added @docsteveharris to review the contents.
Should we also include Sean to validate that no data is exposed?

**Review by uy-rrodriguez — CHANGES_REQUESTED** [review]
PR for project data should not make changes to the base code. Please remove this. You can set the status as "in progress"

**Comment by lawrencelai** [comment]
About the base code changing, I rolled back already after my first commit so no base code has been updated now.
The status has been updated to "on-going".

**Review by docsteveharris — COMMENTED** [review]
Nice work! Added some detail to the summaries

**Review by docsteveharris — APPROVED** [review]

**Review by docsteveharris — APPROVED** [review]

**Comment by lawrencelai** [comment]
Thanks Steve!

**Pull request merged**
