### PR TITLE
Jekyllify at build time / status indicator

### PR DESCRIPTION
**Pull request by tcouch**
Re-opening this pull request as it's changed significantly.

* Introduces project status attribute
  * Status can be one of ongoing or completed (defaults to ongoing)
  * Status is displayed as pill label on project card and next to main heading on project page
* Replaced `authors.txt` and `title.txt` with general config file `metadata.yml` where status can also be set
* Refactored `jekyllify.py` and `check_projects.py`
  * Jekyllify now imports and reuses functions from check_projects where necessary
  * Check projects validates metadata.yml and jekyll front matter
  * Errors raised by both scripts when requirements aren't met
* Incorporated changes from #58 to run Jekyllify at build
* Updated project submission guidance to reflect the above changes (metadata.yml and authors not running jekyllify themselves)

### CODE REVIEW

**Comment by tcouch** [comment]
@uy-rrodriguez I still need to update the guidance for this, but otherwise I think I've done what we discussed.

**Comment by uy-rrodriguez** [comment]
I've read all the changes and it's an excellent work! Haven't tried in my fork, but I feel everything we discussed is there.
Thank you so much!

Let me know when the guidance is updated, and if you need a hand with that.
Otherwise, I think all is good.

**Comment by tcouch** [comment]
> I've read all the changes and it's an excellent work! Haven't tried in my fork, but I feel everything we discussed is there. Thank you so much!
> 
> Let me know when the guidance is updated, and if you need a hand with that. Otherwise, I think all is good.

Thanks Ricardo, I think this is ready.

**Review by uy-rrodriguez — APPROVED** [review]
Excellent. The updates to the guidance seem good as well. Thank you!

**Pull request merged**
